# Generated by Django 2.2.28 on 2024-12-03 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='address',
            field=models.CharField(max_length=128, null=True, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 3, 18, 53, 2, 666606), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 3, 18, 53, 2, 666606), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 3, 18, 53, 2, 667603), null=True, verbose_name='Дата заказа'),
        ),
    ]
