# Generated by Django 2.2.28 on 2024-12-03 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20241203_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 3, 20, 38, 52, 562992), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 3, 20, 38, 52, 562992), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 3, 20, 38, 52, 563989), null=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('Собирем заказ', 'Собирем заказ'), ('Доставляем', 'Доставляем'), ('Доставленно', 'Доставленно'), ('Получено', 'Получено')], max_length=128, null=True, verbose_name='статус заказа'),
        ),
    ]
