# Generated by Django 2.2.28 on 2024-04-14 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240410_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'коментарий статьи', 'verbose_name_plural': 'коментарии статьи'},
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(default='background.jpg', upload_to='', verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 14, 21, 36, 42, 636811), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 14, 21, 36, 42, 637807), verbose_name='Дата публикации'),
        ),
    ]
